name: stockquote
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
#  sdk: '>=3.4.3 <4.0.0'
  sdk: '>=3.4.0-190.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.2.7
  flutter_bloc: ^8.1.6
  google_fonts: ^6.2.1
  hydrated_bloc: ^9.1.5
  equatable: ^2.0.5
  iconsax_flutter: ^1.0.0
  http: ^1.2.2
  toastification: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
